variable "vpc_cidr" {}
variable "region" {}
variable "project_name" {}
variable "public_subnet_1a_cidr" {}
variable "public_subnet_2b_cidr" {}
variable "private_subnet_3a_cidr" {}
variable "private_subnet_4b_cidr" {}
variable "private_subnet_5a_cidr" {}
variable "private_subnet_6b_cidr" {}